Updated README.md for grammatical errors
fireship-io/fireship.io pull request #1715
Opened 2024-01-04 09:46 UTC by hardaatbaath

2024-01-06 10:19 UTC, Helfese approved these changes

2024-01-18 05:20 UTC, makstyle119 requested changes

2024-01-18 05:20 UTC, makstyle119 commented on README.md
> +- `npm run hugo`: Only runs static sites.
using the `site` keyword is correct because here we are talking about the current repo project to `run`

2025-08-23 20:41 UTC, matthewruzzi requested changes

2025-08-23 20:41 UTC, matthewruzzi commented on README.md
> +- `npm run hugo`: Only runs static sites.
```suggestion
- `npm run hugo`: Only runs static site. 
```

2025-09-29 11:32 UTC, closed without merging